apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: prod
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
